export const PERSONAL_INFO = {
  firstName: 'Asad',
  lastName: 'Bangash',
  fullName: 'Asad Bangash',
  initials: 'AB',
  primaryTitle: 'Flutter Developer',
  secondaryTitle: 'Mobile Application Engineer',
  combinedTitle: 'Flutter Developer & Mobile Application Engineer',
  yearsOfExperience: '2+',
  email: 'assadbangash.kust@gmail.com',
  phone: '+923339636238',
  phoneDisplay: '(+92) 333-9636238',
  location: 'Kohat, Pakistan',
  locationShort: 'Kohat, Pakistan',
  country: 'Pakistan',
  city: 'Kohat',
  timezone: 'Asia/Karachi',
  availability: 'Available for Projects',
  availabilityShort: 'Available',
  resumeUrl: '/resume/asad-bangash-resume.pdf',
  resumeFileName: 'Asad-Bangash-Flutter-Developer-Resume.pdf',
  avatarUrl: '/images/profileiamge.png',
  profileImageAlt: 'Asad Bangash, Flutter Developer based in Kohat, Pakistan',
  summary:
    'Flutter Developer with 2+ years of experience building scalable cross-platform mobile applications for fintech, healthcare, edtech, and e-commerce industries. Experienced in shipping production-ready applications to Google Play Store and Apple App Store while integrating real-time systems, payment gateways, Firebase services, and REST APIs. Strong focus on clean architecture, performance optimization, and delivering high-quality user experiences for international clients.',
  shortBio:
    'Building scalable Flutter applications for fintech, healthcare, edtech, and e-commerce. 2+ years shipping production apps to App Store and Play Store.',
  heroTagline: 'Crafting production-ready Flutter apps for global teams.',
  introParagraphs: [
    'I am a Flutter Developer based in Kohat, Pakistan with two plus years of production experience building cross-platform mobile applications that ship to both the Google Play Store and Apple App Store. My focus is on clean architecture, performant rendering, and reliable integrations.',
    'I have worked with international clients from the United Kingdom, United States, Spain, and Germany on fintech, healthcare, edtech, and e-commerce products. I care about maintainable code, scalable structure, and giving end users smooth experiences on real devices.',
    'Currently I am open to freelance engagements, remote roles, and long-term collaborations with teams building serious mobile products.',
  ],
} as const;
