export const SITE_CONFIG = {
  name: 'Asad Bangash',
  shortName: 'Asad Bangash',
  title: 'Asad Bangash — Flutter Developer & Mobile Application Engineer',
  description:
    'Flutter Developer with 2+ years building scalable cross-platform mobile applications for fintech, healthcare, edtech, and e-commerce. Apps shipped to Google Play Store and Apple App Store.',
  tagline: 'Flutter Developer & Mobile Application Engineer',
  author: 'Asad Bangash',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://asadbangash.dev',
  locale: 'en_US',
  language: 'en',
  themeColor: '#0a0a0c',
  backgroundColor: '#0a0a0c',
  ogImage: '/images/og-image.jpg',
  twitterHandle: '@asadbangash',
  type: 'website',
  category: 'Software Engineering Portfolio',
  publishedAt: '2024-01-01',
} as const;

export const SITE_KEYWORDS = [
  'Asad Bangash',
  'Asad Bangash Flutter Developer',
  'Asad Bangash Portfolio',
  'Flutter Developer Pakistan',
  'Flutter Developer Kohat',
  'Mobile Application Engineer',
  'Cross-Platform Mobile Developer',
  'Flutter',
  'Dart',
  'Firebase',
  'Riverpod',
  'Provider',
  'GetX',
  'Clean Architecture Flutter',
  'MVVM Flutter',
  'Stripe Flutter',
  'Reloadly Flutter',
  'ZEGOCLOUD Flutter',
  'Firestore',
  'Firebase Authentication',
  'Firebase Cloud Messaging',
  'Google Maps Flutter',
  'iOS Developer',
  'Android Developer',
  'App Store Developer',
  'Play Store Developer',
  'Fintech Mobile Developer',
  'Healthcare App Developer',
  'EdTech Flutter Developer',
  'E-commerce Flutter Developer',
  'Real-time Chat Flutter',
  'Video Calling Flutter',
  'Push Notifications Flutter',
  'Mobile Engineer for Hire',
  'Freelance Flutter Developer',
  'Remote Flutter Developer',
  'Flutter Developer UK',
  'Flutter Developer USA',
  'Flutter Developer Europe',
] as const;
